# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDc1OGM5NDVlMzc3ZDgxYTk2YzI5M2U5ZGE3M2UzNjBjOGRlOWQ5NTA0ODk3MWEzNjc2ZTlmYWI4N2MzYWEwOWI0MDEzZjkwNWNlNjMzNjc2N2NmMTc3ZWJlZjQwY2U1YzhmNjllMmI1MzhiMzI3MGYzZDY0OTdmYTBkZDQwODI=
